adding curl exit code check

diff --git a/check_response_time b/check_response_time
--- a/check_response_time
+++ b/check_response_time
@@ -147,6 +147,9 @@ for i in $(seq 1 $ITERATIONS); do
   if [[ $EXT_CODE -ne 0 ]]; then
     if [[ $EXT_CODE -eq 127 ]]; then #command not found
       echo "is curl installed? try \"sudo apt-get install curl\" to fix this";exit 1
+    else
+        echo "curl exited with error:$EXT_CODE"
+        exit $EXT_CODE
     fi
   fi
 
